version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
#it is actually 3.9 but this gives error
  version: 3.8
  install:
    - requirements: jinja2 3.1.0
